### ISSUE TITLE
Unable to print results

### ISSUE THREAD

**Issue by pieterboth** [Quantimus/quantimus#2]
Using the most recent version of Anaconda. When I try to print results to excel, I get the following error message:

Traceback (most recent call last):
  File "/Users/pieterboth/.FLIKA/plugins/quantimus/quantimus.py", line 855, in print_data
    workbook.close()
  File "/opt/anaconda3/lib/python3.9/site-packages/xlsxwriter/workbook.py", line 323, in close
    self._store_workbook()
  File "/opt/anaconda3/lib/python3.9/site-packages/xlsxwriter/workbook.py", line 739, in _store_workbook
    xlsx_file.write(os_filename, xml_filename)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1761, in write
    with open(filename, "rb") as src, self.open(zinfo, 'w') as dest:
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1505, in open
    return self._open_to_write(zinfo, force_zip64=force_zip64)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1600, in _open_to_write
    self.fp.write(zinfo.FileHeader(zip64))
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 759, in write
    n = self.fp.write(data)
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by kyleellefsen** [comment]
This looks like a problem with the xlsxwriter library. I'm not super familiar with [this code](https://github.com/Quantimus/quantimus/blob/cbce4bd1645190c75581ebcc5187365e285f84b2/quantimus.py#L840-L855), but it seems from the error like the worksheet object stores a set of operations which actually get written when `workbook.close()` gets called. One possible cause of the above error is that the [`save_file_gui()`](https://github.com/flika-org/flika/blob/68b87e8f75f77f4b59344e418c7783b24184adaa/flika/utils/misc.py#L82) isn't successful. `save_file_gui` returns an an empty string if there is a problem, and nothing in the quantimus code handles that. The [workbook saving code](https://github.com/Quantimus/quantimus/blob/cbce4bd1645190c75581ebcc5187365e285f84b2/quantimus.py#L840-L855) should be modified to handle edge cases like this. 

@pieterboth can you elaborate on what happened prior to this failure? Did a window pop up asking you to select a file name? Did you cancel it?

@Jkastens is anyone maintaining this code now?
