### ISSUE TITLE
Unable to install plugin. `No module named 'xlsxwriter'`

### ISSUE THREAD

**Issue by kyleellefsen** [Quantimus/quantimus#3]
I just created a fresh install of flika on my MacBook (macOS Ventura; Python 3.11.7) and attempted to install this plugin using flika's plugin manager. 

The error message reads:
```python
Traceback (most recent call last):
  File "/Users/kylenv/Desktop/flika_test/flika/flika/app/plugin_manager.py", line 304, in downloadClicked
    PluginManager.downloadPlugin(plugin)
  File "/Users/kylenv/Desktop/flika_test/flika/flika/app/plugin_manager.py", line 492, in downloadPlugin
    build_submenu(plugin.directory, plugin.menu, plugin.menu_layout)
  File "/Users/kylenv/Desktop/flika_test/flika/flika/app/plugin_manager.py", line 118, in build_submenu
    method = str2func(module_name, od['@location'], od['@function'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kylenv/Desktop/flika_test/flika/flika/app/plugin_manager.py", line 98, in str2func
    module = __import__(plugin_dir, fromlist=[levels[0]]).__dict__[levels[0]]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kylenv/.FLIKA/plugins/quantimus/quantimus.py", line 4, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
```

I suspect the problem is that the info.xml file doesn't specify xlsxwriter as a dependency.

**Comment by kyleellefsen** [comment]
Adding the dependency in https://github.com/Quantimus/quantimus/commit/4947d9c06d0a34c0d2e8a0107234cb4668e727ba seemed to fix this.
